version: '3.8'

services:
  # 1. L'APPLICATION WEB (C'est elle qui construit l'image)
  app-staging:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: leyinvest-app-image:latest # Nom donné à l'image construite
    container_name: leyinvest_app_staging
    restart: unless-stopped
    environment:
      - CONTAINER_ROLE=app
      - APP_ENV=staging
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s

  # 2. LE WORKER (Il réutilise l'image construite par l'app)
  worker-staging:
    image: leyinvest-app-image:latest
    container_name: leyinvest_worker_staging
    restart: unless-stopped
    environment:
      - CONTAINER_ROLE=worker
      - APP_ENV=staging
    networks:
      - dokploy-network
    depends_on:
      - app-staging

  # 3. LE SCHEDULER
  scheduler-staging:
    image: leyinvest-app-image:latest
    container_name: leyinvest_scheduler_staging
    restart: unless-stopped
    environment:
      - CONTAINER_ROLE=scheduler
      - APP_ENV=staging
    networks:
      - dokploy-network
    depends_on:
      - app-staging

networks:
  dokploy-network:
    external: true
